export const options = [
  { value: 'normal', label: 'Normal' },
  { value: 'fire', label: 'Fogo' },
  { value: 'water', label: 'Água' },
  { value: 'grass', label: 'Planta' },
  { value: 'flying', label: 'Voador' },
  { value: 'fighting', label: 'Lutador' },
  { value: 'poison', label: 'Venenoso' },
  { value: 'electric', label: 'Elétrico' },
  { value: 'ground', label: 'Terra' },
  { value: 'rock', label: 'Pedra' },
  { value: 'psychic', label: 'Psíquico ' },
  { value: 'ice', label: 'Gelo' },
  { value: 'bug', label: 'Inseto' },
  { value: 'ghost', label: 'Fantasma' },
  { value: 'steel', label: 'Ferro' },
  { value: 'dragon', label: 'Dragão' },
  { value: 'dark', label: 'Sombrio' },
  { value: 'fairy', label: 'Fada' },
];
